name = "XRationals"
uuid = "f354a88b-0804-406d-a35b-636616acac82"
version = "0.1.0"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"

[compat]
BitIntegers = "0.3.7"
Chairmarks = "1.3.1"
julia = "1.10"
